<?xml version="1.0" encoding="utf-8"?><Database Name="AJPO2" Class="BazaDanychDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PRZEMO-KOMPUTER\MOJSERWER;Initial Catalog=AJPO2;Integrated Security=True" SettingsObjectName="WarstwaUslug.Properties.Settings" SettingsPropertyName="AJPO2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Czytelnicy" Member="Czytelnicy">
    <Type Name="Czytelnicy">
      <Column Name="ID_czytelnika" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwisko" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Imie" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Pesel" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="Plec" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NChar(16)" CanBeNull="true" />
      <Association Name="Czytelnicy_Wypozyczenia" Member="Wypozyczenia" ThisKey="ID_czytelnika" OtherKey="ID_czytelnika" Type="Wypozyczenia" />
    </Type>
  </Table>
  <Table Name="dbo.Wypozyczenia" Member="Wypozyczenia">
    <Type Name="Wypozyczenia">
      <Column Name="ID_wypozyczenia" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_czytelnika" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sygnatura" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Tytul_ksiazki" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Autor" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Gatunek" Type="System.String" DbType="NChar(25)" CanBeNull="true" />
      <Column Name="Kara" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Czytelnicy_Wypozyczenia" Member="Czytelnicy" ThisKey="ID_czytelnika" OtherKey="ID_czytelnika" Type="Czytelnicy" IsForeignKey="true" />
    </Type>
  </Table>
</Database>