#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarstwaUslug
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AJPO2")]
	public partial class BazaDanychDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCzytelnicy(Czytelnicy instance);
    partial void UpdateCzytelnicy(Czytelnicy instance);
    partial void DeleteCzytelnicy(Czytelnicy instance);
    partial void InsertWypozyczenia(Wypozyczenia instance);
    partial void UpdateWypozyczenia(Wypozyczenia instance);
    partial void DeleteWypozyczenia(Wypozyczenia instance);
    #endregion
		
		public BazaDanychDataContext() : 
				base(global::WarstwaUslug.Properties.Settings.Default.AJPO2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDanychDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDanychDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDanychDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BazaDanychDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Czytelnicy> Czytelnicy
		{
			get
			{
				return this.GetTable<Czytelnicy>();
			}
		}
		
		public System.Data.Linq.Table<Wypozyczenia> Wypozyczenia
		{
			get
			{
				return this.GetTable<Wypozyczenia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Czytelnicy")]
	public partial class Czytelnicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_czytelnika;
		
		private string _Nazwisko;
		
		private string _Imie;
		
		private string _Pesel;
		
		private System.Nullable<char> _Plec;
		
		private string _Telefon;
		
		private EntitySet<Wypozyczenia> _Wypozyczenia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_czytelnikaChanging(int value);
    partial void OnID_czytelnikaChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnPeselChanging(string value);
    partial void OnPeselChanged();
    partial void OnPlecChanging(System.Nullable<char> value);
    partial void OnPlecChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    #endregion
		
		public Czytelnicy()
		{
			this._Wypozyczenia = new EntitySet<Wypozyczenia>(new Action<Wypozyczenia>(this.attach_Wypozyczenia), new Action<Wypozyczenia>(this.detach_Wypozyczenia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_czytelnika", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_czytelnika
		{
			get
			{
				return this._ID_czytelnika;
			}
			set
			{
				if ((this._ID_czytelnika != value))
				{
					this.OnID_czytelnikaChanging(value);
					this.SendPropertyChanging();
					this._ID_czytelnika = value;
					this.SendPropertyChanged("ID_czytelnika");
					this.OnID_czytelnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="NChar(50)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="NChar(50)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pesel", DbType="NChar(11)")]
		public string Pesel
		{
			get
			{
				return this._Pesel;
			}
			set
			{
				if ((this._Pesel != value))
				{
					this.OnPeselChanging(value);
					this.SendPropertyChanging();
					this._Pesel = value;
					this.SendPropertyChanged("Pesel");
					this.OnPeselChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plec", DbType="NChar(1)")]
		public System.Nullable<char> Plec
		{
			get
			{
				return this._Plec;
			}
			set
			{
				if ((this._Plec != value))
				{
					this.OnPlecChanging(value);
					this.SendPropertyChanging();
					this._Plec = value;
					this.SendPropertyChanged("Plec");
					this.OnPlecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NChar(16)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czytelnicy_Wypozyczenia", Storage="_Wypozyczenia", ThisKey="ID_czytelnika", OtherKey="ID_czytelnika")]
		public EntitySet<Wypozyczenia> Wypozyczenia
		{
			get
			{
				return this._Wypozyczenia;
			}
			set
			{
				this._Wypozyczenia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypozyczenia(Wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.Czytelnicy = this;
		}
		
		private void detach_Wypozyczenia(Wypozyczenia entity)
		{
			this.SendPropertyChanging();
			entity.Czytelnicy = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wypozyczenia")]
	public partial class Wypozyczenia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_wypozyczenia;
		
		private System.Nullable<int> _ID_czytelnika;
		
		private string _Sygnatura;
		
		private string _Tytul_ksiazki;
		
		private string _Autor;
		
		private string _Gatunek;
		
		private System.Nullable<double> _Kara;
		
		private EntityRef<Czytelnicy> _Czytelnicy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_wypozyczeniaChanging(int value);
    partial void OnID_wypozyczeniaChanged();
    partial void OnID_czytelnikaChanging(System.Nullable<int> value);
    partial void OnID_czytelnikaChanged();
    partial void OnSygnaturaChanging(string value);
    partial void OnSygnaturaChanged();
    partial void OnTytul_ksiazkiChanging(string value);
    partial void OnTytul_ksiazkiChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnGatunekChanging(string value);
    partial void OnGatunekChanged();
    partial void OnKaraChanging(System.Nullable<double> value);
    partial void OnKaraChanged();
    #endregion
		
		public Wypozyczenia()
		{
			this._Czytelnicy = default(EntityRef<Czytelnicy>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_wypozyczenia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_wypozyczenia
		{
			get
			{
				return this._ID_wypozyczenia;
			}
			set
			{
				if ((this._ID_wypozyczenia != value))
				{
					this.OnID_wypozyczeniaChanging(value);
					this.SendPropertyChanging();
					this._ID_wypozyczenia = value;
					this.SendPropertyChanged("ID_wypozyczenia");
					this.OnID_wypozyczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_czytelnika", DbType="Int")]
		public System.Nullable<int> ID_czytelnika
		{
			get
			{
				return this._ID_czytelnika;
			}
			set
			{
				if ((this._ID_czytelnika != value))
				{
					if (this._Czytelnicy.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_czytelnikaChanging(value);
					this.SendPropertyChanging();
					this._ID_czytelnika = value;
					this.SendPropertyChanged("ID_czytelnika");
					this.OnID_czytelnikaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sygnatura", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string Sygnatura
		{
			get
			{
				return this._Sygnatura;
			}
			set
			{
				if ((this._Sygnatura != value))
				{
					this.OnSygnaturaChanging(value);
					this.SendPropertyChanging();
					this._Sygnatura = value;
					this.SendPropertyChanged("Sygnatura");
					this.OnSygnaturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytul_ksiazki", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Tytul_ksiazki
		{
			get
			{
				return this._Tytul_ksiazki;
			}
			set
			{
				if ((this._Tytul_ksiazki != value))
				{
					this.OnTytul_ksiazkiChanging(value);
					this.SendPropertyChanging();
					this._Tytul_ksiazki = value;
					this.SendPropertyChanged("Tytul_ksiazki");
					this.OnTytul_ksiazkiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="NChar(50)")]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this.OnAutorChanging(value);
					this.SendPropertyChanging();
					this._Autor = value;
					this.SendPropertyChanged("Autor");
					this.OnAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gatunek", DbType="NChar(25)")]
		public string Gatunek
		{
			get
			{
				return this._Gatunek;
			}
			set
			{
				if ((this._Gatunek != value))
				{
					this.OnGatunekChanging(value);
					this.SendPropertyChanging();
					this._Gatunek = value;
					this.SendPropertyChanged("Gatunek");
					this.OnGatunekChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kara", DbType="Float")]
		public System.Nullable<double> Kara
		{
			get
			{
				return this._Kara;
			}
			set
			{
				if ((this._Kara != value))
				{
					this.OnKaraChanging(value);
					this.SendPropertyChanging();
					this._Kara = value;
					this.SendPropertyChanged("Kara");
					this.OnKaraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czytelnicy_Wypozyczenia", Storage="_Czytelnicy", ThisKey="ID_czytelnika", OtherKey="ID_czytelnika", IsForeignKey=true)]
		public Czytelnicy Czytelnicy
		{
			get
			{
				return this._Czytelnicy.Entity;
			}
			set
			{
				Czytelnicy previousValue = this._Czytelnicy.Entity;
				if (((previousValue != value) 
							|| (this._Czytelnicy.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Czytelnicy.Entity = null;
						previousValue.Wypozyczenia.Remove(this);
					}
					this._Czytelnicy.Entity = value;
					if ((value != null))
					{
						value.Wypozyczenia.Add(this);
						this._ID_czytelnika = value.ID_czytelnika;
					}
					else
					{
						this._ID_czytelnika = default(Nullable<int>);
					}
					this.SendPropertyChanged("Czytelnicy");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
